baseURL: https://philipptempel.gitlab.io/latex-package/
languageCode: en-us
title: Philipp Tempels LaTeX
theme: book

# Book configuration
disablePathToLower: false
enableGitInfo: true
disableKinds:
  - taxonomy
  - taxonomyTerm
params:
  BookComments: false
  BookRepo: https://philipptempel.gitlab.io/latex-package/
  BookEditPath: -/edit/docs/content/
  BookToC: true
